name: Build and Deploy a Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # include the lines below if you are using jekyll-last-modified-at
        # or if you would otherwise need to fetch the full commit history
        # however this may be very slow for large repositories!
        # with:
        # fetch-depth: '0'
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4

      - name: Install & Build
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          FOLDER: ./_site